name: workflow1
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Name
        run : echo "This is rahul sharma"
    
      - name: Checkout code from github 
        uses: actions/checkout@v4
